version: '3.7'

services:
  notebook:
    build: .
    platform: linux/amd64
    restart: unless-stopped
    working_dir: "/home/work"
    environment:
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    ports:
      - 10000:8888
    volumes:
      - .:/home/work:cached